# Generated by Django 3.2.25 on 2026-05-18 04:37
#
# Hand-edited 2026-05-19: replaced the auto-generated CreateModel with a
# RunSQL + state_operations pair. Django infers the FK column type from the
# referenced model's PK state; because catalogue.Layer.id is implicit and the
# project sets DEFAULT_AUTO_FIELD = BigAutoField (webapp/settings.py), Django
# generates BIGINT for layer_id. The actual catalogue_layer.id column on prod
# (and in the captured schema snapshot) is INT IDENTITY(1,1), so the
# autogenerated migration fails FK type-checking on SQL Server.
#
# Fixing it on the catalogue side would emit a 49-statement PK rebuild on a
# load-bearing table — separate prod-deploy concern. This migration scopes the
# workaround to nhat alone: raw SQL creates layer_id as INT, while
# state_operations keeps the ORM's view of NhatLayer.layer as a OneToOneField
# so application code is unchanged.

from django.db import migrations, models
import django.db.models.deletion


COLOR_PALETTE_CHOICES = [
    ('default', 'default'), ('div-BrBG', 'div-BrBG'), ('div-BuRd', 'div-BuRd'),
    ('div-BuRd2', 'div-BuRd2'), ('div-PRGn', 'div-PRGn'), ('div-PiYG', 'div-PiYG'),
    ('div-PuOr', 'div-PuOr'), ('div-RdBu', 'div-RdBu'), ('div-RdGy', 'div-RdGy'),
    ('div-RdYlBu', 'div-RdYlBu'), ('div-RdYlGn', 'div-RdYlGn'),
    ('div-Spectral', 'div-Spectral'), ('psu-inferno', 'psu-inferno'),
    ('psu-magma', 'psu-magma'), ('psu-plasma', 'psu-plasma'),
    ('psu-viridis', 'psu-viridis'), ('seq-BkBu', 'seq-BkBu'),
    ('seq-BkGn', 'seq-BkGn'), ('seq-BkRd', 'seq-BkRd'), ('seq-BkYl', 'seq-BkYl'),
    ('seq-BlueHeat', 'seq-BlueHeat'), ('seq-Blues', 'seq-Blues'),
    ('seq-BuGn', 'seq-BuGn'), ('seq-BuPu', 'seq-BuPu'), ('seq-BuYl', 'seq-BuYl'),
    ('seq-GnBu', 'seq-GnBu'), ('seq-Greens', 'seq-Greens'),
    ('seq-Greys', 'seq-Greys'), ('seq-GreysRev', 'seq-GreysRev'),
    ('seq-Heat', 'seq-Heat'), ('seq-OrRd', 'seq-OrRd'),
    ('seq-Oranges', 'seq-Oranges'), ('seq-PuBu', 'seq-PuBu'),
    ('seq-PuBuGn', 'seq-PuBuGn'), ('seq-PuRd', 'seq-PuRd'),
    ('seq-Purples', 'seq-Purples'), ('seq-RdPu', 'seq-RdPu'),
    ('seq-Reds', 'seq-Reds'), ('seq-YlGn', 'seq-YlGn'),
    ('seq-YlGnBu', 'seq-YlGnBu'), ('seq-YlOrBr', 'seq-YlOrBr'),
    ('seq-YlOrRd', 'seq-YlOrRd'), ('seq-cubeYF', 'seq-cubeYF'),
    ('x-Ncview', 'x-Ncview'), ('x-Occam', 'x-Occam'),
    ('x-Rainbow', 'x-Rainbow'), ('x-Sst', 'x-Sst'),
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0034_auto_20260518_0437'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                CREATE TABLE [nhat_nhatlayer] (
                    [layer_id] int NOT NULL PRIMARY KEY,
                    [color_scale_range_min] int NOT NULL,
                    [color_scale_range_max] int NOT NULL,
                    [above_max_color] nvarchar(8) NOT NULL,
                    [below_min_color] nvarchar(8) NOT NULL,
                    [color_palette] nvarchar(50) NOT NULL
                );
                """,
                """
                ALTER TABLE [nhat_nhatlayer]
                    ADD CONSTRAINT [nhat_nhatlayer_layer_id_fk_catalogue_layer_id]
                    FOREIGN KEY ([layer_id]) REFERENCES [catalogue_layer] ([id]);
                """,
            ],
            reverse_sql=[
                "DROP TABLE [nhat_nhatlayer];",
            ],
            state_operations=[
                migrations.CreateModel(
                    name='NhatLayer',
                    fields=[
                        ('layer', models.OneToOneField(
                            on_delete=django.db.models.deletion.CASCADE,
                            primary_key=True,
                            serialize=False,
                            to='catalogue.layer',
                        )),
                        ('color_scale_range_min', models.IntegerField(default=0)),
                        ('color_scale_range_max', models.IntegerField(default=100)),
                        ('above_max_color', models.CharField(default='0x000000', max_length=8)),
                        ('below_min_color', models.CharField(default='0x000000', max_length=8)),
                        ('color_palette', models.CharField(
                            choices=COLOR_PALETTE_CHOICES,
                            default='default',
                            max_length=50,
                        )),
                    ],
                ),
            ],
        ),
    ]
