# Generated by Django 4.2.25 on 2026-05-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0034_alter_layer_layer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhatLayer',
            fields=[
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalogue.layer')),
                ('color_scale_range_min', models.IntegerField(default=0)),
                ('color_scale_range_max', models.IntegerField(default=100)),
                ('above_max_color', models.CharField(default='0x000000', max_length=8)),
                ('below_min_color', models.CharField(default='0x000000', max_length=8)),
                ('color_palette', models.CharField(choices=[('default', 'default'), ('div-BrBG', 'div-BrBG'), ('div-BuRd', 'div-BuRd'), ('div-BuRd2', 'div-BuRd2'), ('div-PRGn', 'div-PRGn'), ('div-PiYG', 'div-PiYG'), ('div-PuOr', 'div-PuOr'), ('div-RdBu', 'div-RdBu'), ('div-RdGy', 'div-RdGy'), ('div-RdYlBu', 'div-RdYlBu'), ('div-RdYlGn', 'div-RdYlGn'), ('div-Spectral', 'div-Spectral'), ('psu-inferno', 'psu-inferno'), ('psu-magma', 'psu-magma'), ('psu-plasma', 'psu-plasma'), ('psu-viridis', 'psu-viridis'), ('seq-BkBu', 'seq-BkBu'), ('seq-BkGn', 'seq-BkGn'), ('seq-BkRd', 'seq-BkRd'), ('seq-BkYl', 'seq-BkYl'), ('seq-BlueHeat', 'seq-BlueHeat'), ('seq-Blues', 'seq-Blues'), ('seq-BuGn', 'seq-BuGn'), ('seq-BuPu', 'seq-BuPu'), ('seq-BuYl', 'seq-BuYl'), ('seq-GnBu', 'seq-GnBu'), ('seq-Greens', 'seq-Greens'), ('seq-Greys', 'seq-Greys'), ('seq-GreysRev', 'seq-GreysRev'), ('seq-Heat', 'seq-Heat'), ('seq-OrRd', 'seq-OrRd'), ('seq-Oranges', 'seq-Oranges'), ('seq-PuBu', 'seq-PuBu'), ('seq-PuBuGn', 'seq-PuBuGn'), ('seq-PuRd', 'seq-PuRd'), ('seq-Purples', 'seq-Purples'), ('seq-RdPu', 'seq-RdPu'), ('seq-Reds', 'seq-Reds'), ('seq-YlGn', 'seq-YlGn'), ('seq-YlGnBu', 'seq-YlGnBu'), ('seq-YlOrBr', 'seq-YlOrBr'), ('seq-YlOrRd', 'seq-YlOrRd'), ('seq-cubeYF', 'seq-cubeYF'), ('x-Ncview', 'x-Ncview'), ('x-Occam', 'x-Occam'), ('x-Rainbow', 'x-Rainbow'), ('x-Sst', 'x-Sst')], default='default', max_length=50)),
            ],
        ),
    ]
