# Generated by Django 3.2.25 on 2026-05-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_auto_20260518_0437'),
        ('nhat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NhatLayer',
            new_name='HazardLayer',
        ),
    ]
