# Generated by Django 3.2.25 on 2026-05-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0003_scenario_scientificmodel_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='sort_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scientificmodel',
            name='sort_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='sort_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
