# Generated by Django 3.2.25 on 2026-06-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0004_auto_20260522_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmipPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_key', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'CMIP Phase',
            },
        ),
    ]
