# Generated by Django 4.2.28 on 2026-06-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0005_cmipphase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmipphase',
            options={'verbose_name': 'CMIP phase'},
        ),
        migrations.AlterField(
            model_name='cmipphase',
            name='name',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='scientificmodel',
            name='name',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
