# Generated by Django 4.2.28 on 2026-06-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0006_alter_cmipphase_options_alter_cmipphase_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmipphase',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scientificmodel',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
