# Generated by Django 4.2.28 on 2026-06-24 04:02

from django.db import migrations
from django.db.models import F


def copy_names_to_display_names(apps, schema_editor):
    CmipPhase = apps.get_model("nhat", "CmipPhase")
    ScientificModel = apps.get_model("nhat", "ScientificModel")
    Scenario = apps.get_model("nhat", "Scenario")
    Season = apps.get_model("nhat", "Season")

    CmipPhase.objects.update(display_name=F("name"))
    ScientificModel.objects.update(display_name=F("name"))
    Scenario.objects.update(display_name=F("name"))
    Season.objects.update(display_name=F("name"))


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0007_cmipphase_display_name_scenario_display_name_and_more'),
    ]

    operations = [
        migrations.RunPython(
            copy_names_to_display_names,
            migrations.RunPython.noop,
        ),
    ]
