# Generated by Django 4.2.28 on 2026-06-24 04:02

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.models import F


# mypy: disable-error-code="misc"


def copy_names_to_display_names(apps: Apps, _schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Copy name field values to display_name field for all models."""
    cmip_phase = apps.get_model("nhat", "CmipPhase")
    scientific_model = apps.get_model("nhat", "ScientificModel")
    scenario = apps.get_model("nhat", "Scenario")
    season = apps.get_model("nhat", "Season")

    cmip_phase.objects.update(display_name=F("name"))
    scientific_model.objects.update(display_name=F("name"))
    scenario.objects.update(display_name=F("name"))
    season.objects.update(display_name=F("name"))


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0007_cmipphase_display_name_scenario_display_name_and_more'),
    ]

    operations = [
        migrations.RunPython(
            copy_names_to_display_names,
            migrations.RunPython.noop,
        ),
    ]
