# Generated by Django 4.2.28 on 2026-06-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0008_copy_names_to_display_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmipphase',
            name='display_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='display_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='scientificmodel',
            name='display_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='display_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
