# Generated by Django 4.2.28 on 2026-06-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0009_alter_cmipphase_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmipphase',
            name='scientific_models',
            field=models.ManyToManyField(to='nhat.scientificmodel'),
        ),
        migrations.AddField(
            model_name='scientificmodel',
            name='scenarios',
            field=models.ManyToManyField(to='nhat.scenario'),
        ),
    ]
