# Generated by Django 4.2.28 on 2026-07-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0010_cmipphase_scientific_models_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmipphase',
            name='display_name',
            field=models.CharField(help_text='Name displayed for this CMIP phase in the interactive map.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cmipphase',
            name='name',
            field=models.SlugField(help_text='\n            Unique slug used for the NetCDF file name to associate it with this CMIP phase.\n        ', unique=True),
        ),
        migrations.AlterField(
            model_name='cmipphase',
            name='scientific_models',
            field=models.ManyToManyField(help_text='Scientific models available under this scientific CMIP phase.', to='nhat.scientificmodel'),
        ),
        migrations.AlterField(
            model_name='cmipphase',
            name='sort_key',
            field=models.CharField(blank=True, help_text='\n            Determines the order CMIP phases are shown in the app. Sorted\n            alphabetically/numerically, with blanks last. First CMIP phase in order is the\n            default selection when the app is first loaded.\n        ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='display_name',
            field=models.CharField(help_text='Name displayed for this scenario in the interactive map.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.SlugField(help_text='\n            Unique slug used for the NetCDF file name to associate it with this scenario.\n        ', unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='sort_key',
            field=models.CharField(blank=True, help_text='\n            Determines the order scenarios are shown in the app. Sorted\n            alphabetically/numerically, with blanks last. First scenario in order is the\n            default selection when the app is first loaded.\n        ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scientificmodel',
            name='display_name',
            field=models.CharField(help_text='Name displayed for this model in the interactive map.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='scientificmodel',
            name='name',
            field=models.SlugField(help_text='\n            Unique slug used for the NetCDF file name to associate it with this model.\n        ', unique=True),
        ),
        migrations.AlterField(
            model_name='scientificmodel',
            name='scenarios',
            field=models.ManyToManyField(help_text='Scenarios available under this scientific model.', to='nhat.scenario'),
        ),
        migrations.AlterField(
            model_name='scientificmodel',
            name='sort_key',
            field=models.CharField(blank=True, help_text='\n            Determines the order scientific models are shown in the app. Sorted\n            alphabetically/numerically, with blanks last. First model in order is the\n            default selection when the app is first loaded.\n        ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='display_name',
            field=models.CharField(help_text='Name displayed for this season in the interactive map.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.SlugField(help_text='\n            Unique slug used for the NetCDF file name to associate it with this season.\n        ', unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='sort_key',
            field=models.CharField(blank=True, help_text='\n            Determines the order seasons are shown in the app. Sorted alphabetically/numerically, with blanks last. First CMIP phase in order is the default selection when the app is first loaded.\n        ', max_length=10, null=True),
        ),
    ]
