# Generated by Django 4.2.28 on 2026-07-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0011_alter_cmipphase_display_name_alter_cmipphase_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmipphase',
            name='scientific_models',
        ),
        migrations.RemoveField(
            model_name='scientificmodel',
            name='scenarios',
        ),
    ]
