# Generated by Django 4.2.28 on 2026-07-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0012_remove_cmipphase_scientific_models_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificmodel',
            name='data_category',
            field=models.CharField(choices=[('ensemble_statistic', 'ensemble_statistic'), ('model', 'model')], default='model', max_length=50),
            preserve_default=False,
        ),
    ]
