# Generated by Django 4.2.28 on 2026-07-06 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_layer_metadata_content'),
        ('nhat', '0013_scientificmodel_data_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardlayer',
            name='color_scale_range_max',
        ),
        migrations.RemoveField(
            model_name='hazardlayer',
            name='color_scale_range_min',
        ),
        migrations.AlterField(
            model_name='hazardlayer',
            name='layer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='catalogue.layer'),
        ),
        migrations.CreateModel(
            name='HazardLayerDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_scale_range_min', models.FloatField(default=0)),
                ('color_scale_range_max', models.FloatField(default=100)),
                ('is_historical', models.BooleanField(default=False)),
                ('cmip_phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='nhat.cmipphase')),
                ('hazard_layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='nhat.hazardlayer')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='nhat.scenario')),
                ('scientific_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='nhat.scientificmodel')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='nhat.season')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hazardlayerdataset',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_historical', True), ('scenario__isnull', True)), models.Q(('is_historical', False), ('scenario__isnull', False)), _connector='OR'), name='historical_requires_null_scenario'),
        ),
        migrations.AddConstraint(
            model_name='hazardlayerdataset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_historical', True)), fields=('hazard_layer', 'cmip_phase', 'scientific_model', 'season'), name='unique_historical_dataset'),
        ),
        migrations.AddConstraint(
            model_name='hazardlayerdataset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_historical', False)), fields=('hazard_layer', 'cmip_phase', 'scientific_model', 'scenario', 'season'), name='unique_projected_dataset'),
        ),
    ]
