# Generated by Django 4.2.28 on 2026-07-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0014_remove_hazardlayer_color_scale_range_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardlayer',
            name='name',
            field=models.SlugField(default='', help_text='\n            Unique slug used for the NetCDF file name to associate it with this hazard layer.\n        ', unique=True),
            preserve_default=False,
        ),
    ]
