# Generated by Django 4.2.28 on 2026-07-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0015_hazardlayer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardlayer',
            name='human_readable_units',
            field=models.CharField(default='units', max_length=50),
        ),
    ]
