# Generated by Django 4.2.28 on 2026-07-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0016_hazardlayer_human_readable_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardlayer',
            name='color_palette',
            field=models.CharField(choices=[('default', 'default'), ('default-inv', 'default-inv'), ('div-BrBG', 'div-BrBG'), ('div-BrBG-inv', 'div-BrBG-inv'), ('div-BuRd', 'div-BuRd'), ('div-BuRd-inv', 'div-BuRd-inv'), ('div-BuRd2', 'div-BuRd2'), ('div-BuRd2-inv', 'div-BuRd2-inv'), ('div-PRGn', 'div-PRGn'), ('div-PRGn-inv', 'div-PRGn-inv'), ('div-PiYG', 'div-PiYG'), ('div-PiYG-inv', 'div-PiYG-inv'), ('div-PuOr', 'div-PuOr'), ('div-PuOr-inv', 'div-PuOr-inv'), ('div-RdBu', 'div-RdBu'), ('div-RdBu-inv', 'div-RdBu-inv'), ('div-RdGy', 'div-RdGy'), ('div-RdGy-inv', 'div-RdGy-inv'), ('div-RdYlBu', 'div-RdYlBu'), ('div-RdYlBu-inv', 'div-RdYlBu-inv'), ('div-RdYlGn', 'div-RdYlGn'), ('div-RdYlGn-inv', 'div-RdYlGn-inv'), ('div-Spectral', 'div-Spectral'), ('div-Spectral-inv', 'div-Spectral-inv'), ('psu-inferno', 'psu-inferno'), ('psu-inferno-inv', 'psu-inferno-inv'), ('psu-magma', 'psu-magma'), ('psu-magma-inv', 'psu-magma-inv'), ('psu-plasma', 'psu-plasma'), ('psu-plasma-inv', 'psu-plasma-inv'), ('psu-viridis', 'psu-viridis'), ('psu-viridis-inv', 'psu-viridis-inv'), ('seq-BkBu', 'seq-BkBu'), ('seq-BkBu-inv', 'seq-BkBu-inv'), ('seq-BkGn', 'seq-BkGn'), ('seq-BkGn-inv', 'seq-BkGn-inv'), ('seq-BkRd', 'seq-BkRd'), ('seq-BkRd-inv', 'seq-BkRd-inv'), ('seq-BkYl', 'seq-BkYl'), ('seq-BkYl-inv', 'seq-BkYl-inv'), ('seq-BlueHeat', 'seq-BlueHeat'), ('seq-BlueHeat-inv', 'seq-BlueHeat-inv'), ('seq-Blues', 'seq-Blues'), ('seq-Blues-inv', 'seq-Blues-inv'), ('seq-BuGn', 'seq-BuGn'), ('seq-BuGn-inv', 'seq-BuGn-inv'), ('seq-BuPu', 'seq-BuPu'), ('seq-BuPu-inv', 'seq-BuPu-inv'), ('seq-BuYl', 'seq-BuYl'), ('seq-BuYl-inv', 'seq-BuYl-inv'), ('seq-GnBu', 'seq-GnBu'), ('seq-GnBu-inv', 'seq-GnBu-inv'), ('seq-Greens', 'seq-Greens'), ('seq-Greens-inv', 'seq-Greens-inv'), ('seq-Greys', 'seq-Greys'), ('seq-Greys-inv', 'seq-Greys-inv'), ('seq-GreysRev', 'seq-GreysRev'), ('seq-GreysRev-inv', 'seq-GreysRev-inv'), ('seq-Heat', 'seq-Heat'), ('seq-Heat-inv', 'seq-Heat-inv'), ('seq-OrRd', 'seq-OrRd'), ('seq-OrRd-inv', 'seq-OrRd-inv'), ('seq-Oranges', 'seq-Oranges'), ('seq-Oranges-inv', 'seq-Oranges-inv'), ('seq-PuBu', 'seq-PuBu'), ('seq-PuBu-inv', 'seq-PuBu-inv'), ('seq-PuBuGn', 'seq-PuBuGn'), ('seq-PuBuGn-inv', 'seq-PuBuGn-inv'), ('seq-PuRd', 'seq-PuRd'), ('seq-PuRd-inv', 'seq-PuRd-inv'), ('seq-Purples', 'seq-Purples'), ('seq-Purples-inv', 'seq-Purples-inv'), ('seq-RdPu', 'seq-RdPu'), ('seq-RdPu-inv', 'seq-RdPu-inv'), ('seq-Reds', 'seq-Reds'), ('seq-Reds-inv', 'seq-Reds-inv'), ('seq-YlGn', 'seq-YlGn'), ('seq-YlGn-inv', 'seq-YlGn-inv'), ('seq-YlGnBu', 'seq-YlGnBu'), ('seq-YlGnBu-inv', 'seq-YlGnBu-inv'), ('seq-YlOrBr', 'seq-YlOrBr'), ('seq-YlOrBr-inv', 'seq-YlOrBr-inv'), ('seq-YlOrRd', 'seq-YlOrRd'), ('seq-YlOrRd-inv', 'seq-YlOrRd-inv'), ('seq-cubeYF', 'seq-cubeYF'), ('seq-cubeYF-inv', 'seq-cubeYF-inv'), ('x-Ncview', 'x-Ncview'), ('x-Ncview-inv', 'x-Ncview-inv'), ('x-Occam', 'x-Occam'), ('x-Occam-inv', 'x-Occam-inv'), ('x-Rainbow', 'x-Rainbow'), ('x-Rainbow-inv', 'x-Rainbow-inv'), ('x-Sst', 'x-Sst'), ('x-Sst-inv', 'x-Sst-inv')], default='default', max_length=50),
        ),
    ]
