# Generated by Django 4.2.28 on 2026-07-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0017_alter_hazardlayer_color_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificmodel',
            name='display_name',
            field=models.CharField(help_text='Name displayed for this model in the interactive map.', max_length=200, unique=True),
        ),
    ]
