# Generated by Django 4.2.28 on 2026-07-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhat', '0018_alter_scientificmodel_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificmodel',
            name='name',
            field=models.SlugField(help_text='\n            Unique slug used for the NetCDF file name to associate it with this model.\n        ', max_length=200, unique=True),
        ),
    ]
