"""Emit a SQL baseline for Django's migration recorder, derived from the
codebase's on-disk migrations.

Writes one ``INSERT INTO [dbo].[django_migrations] (...) VALUES (...)`` per
migration node in ``MigrationLoader.graph``, sorted by ``(app, name)``. The
``applied`` timestamp is normalised to a constant so captures diff cleanly.

Used at capture time by ``scripts/capture-schema.sh``; the resulting file is
applied by ``backend/docker/dbinit.py`` alongside ``schema.sql`` so that the
local ``django_migrations`` table looks already-migrated to Django at boot.
Plain ``manage.py migrate`` is then a no-op for baselined migrations, and
``post_migrate`` signals fire to populate ``django_content_type`` and
``auth_permission`` from ``INSTALLED_APPS``.

Reads on-disk migrations only — no DB connection needed (passes
``connection=None`` to ``MigrationLoader``). Output goes to stdout.

Modelled on imas-craybase's command of the same name.
"""
from __future__ import annotations

from django.core.management.base import BaseCommand
from django.db.migrations.loader import MigrationLoader


# Constant timestamp so re-runs produce byte-identical output. Only (app, name)
# is meaningful to Django's MigrationRecorder; `applied` is column furniture.
APPLIED = "2000-01-01T00:00:00"


def _quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


class Command(BaseCommand):
    help = (
        "Print INSERT statements that baseline django_migrations from the "
        "codebase's on-disk migration files."
    )

    def handle(self, *args, **options):
        loader = MigrationLoader(connection=None)
        nodes = sorted(loader.graph.nodes)

        out = self.stdout
        out.write(
            "-- Generated by manage.py dump_migration_baseline.\n"
            "-- Baseline rows for django_migrations, derived from the codebase's\n"
            "-- on-disk migration graph at capture time. Apply with:\n"
            "--   sqlcmd -i migrations_baseline.sql -v DatabaseName=<target>\n"
            f"-- Rows: {len(nodes)}\n"
        )
        out.write("USE [$(DatabaseName)];\nGO\n")
        for app, name in nodes:
            out.write(
                "INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) "
                f"VALUES ({_quote(app)}, {_quote(name)}, {_quote(APPLIED)});\n"
            )
        out.write("GO\n")
