-- =============================================
-- Author:		Khanh Nguyen
-- Create date: 12/09/2022
-- Description:	Procedure to transform data for Global Archive Deployment Points
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[IMPORT_GLOBALARCHIVE_DEPLOYMENT_POINTS]
AS
BEGIN
    BEGIN TRANSACTION
    BEGIN TRY
        -- SET NOCOUNT ON added to prevent extra result sets from
        -- interfering with SELECT statements.
        SET NOCOUNT ON;

        -- Vars for cursor
        DECLARE @FID nvarchar(255)
        DECLARE @CAMPAIGN_ID nvarchar(255)
        DECLARE @DEPLOYMENT_ID nvarchar(255)
        DECLARE @DEPLOYMENT_TIME nvarchar(255)
        DECLARE @DESCRIPTION nvarchar(255)
        DECLARE @DEPTH nvarchar(255)
        DECLARE @SITE nvarchar(255)
        DECLARE @STATUS nvarchar(255)
        DECLARE @SUCCESSFUL_COUNT nvarchar(255)
        DECLARE @SUCCESSFUL_LENGTH nvarchar(255)
        DECLARE @COORDINATES nvarchar(255)
        DECLARE @OBSERVER nvarchar(255)
        DECLARE @LOCATION nvarchar(255)
        DECLARE @CAMPAIGN_NAME nvarchar(255)
        DECLARE @CAMPAIGN_LINK nvarchar(255)
        DECLARE @PROJECT_NAME nvarchar(255)
        DECLARE @METHOD_NAME nvarchar(255)
        DECLARE @COLOUR nvarchar(255)
        DECLARE @GEOM geometry


        -- Vars for lookup ID's
        DECLARE @destCAMPAIGN_ID int
        DECLARE @destDEPLOYMENT_ID int
        DECLARE @destDEPLOYMENT_TIME datetime
        DECLARE @destDEPTH int

        DECLARE cGLOBALARCHIVEDATA CURSOR FOR
            SELECT FID, CAMPAIGN_ID, DEPLOYMENT_ID, DEPLOYMENT_TIME, DESCRIPTION, [DEPTH], SITE, STATUS,
                   SUCCESSFUL_COUNT, SUCCESSFUL_LENGTH, COORDINATES, OBSERVER, LOCATION, CAMPAIGN_NAME, CAMPAIGN_LINK, PROJECT_NAME, METHOD_NAME, COLOUR, GEOM
            FROM EXTRACT_GLOBALARCHIVE_DEPLOYMENT_POINTS;

        OPEN cGLOBALARCHIVEDATA

        FETCH NEXT FROM cGLOBALARCHIVEDATA INTO @FID, @CAMPAIGN_ID, @DEPLOYMENT_ID, @DEPLOYMENT_TIME, @DESCRIPTION, @DEPTH, @SITE, @STATUS,
                   @SUCCESSFUL_COUNT, @SUCCESSFUL_LENGTH, @COORDINATES, @OBSERVER, @LOCATION, @CAMPAIGN_NAME, @CAMPAIGN_LINK, @PROJECT_NAME, @METHOD_NAME, @COLOUR, @GEOM
        WHILE @@FETCH_STATUS = 0
        BEGIN


            SET @destCAMPAIGN_ID = CONVERT(INT, @CAMPAIGN_ID)
            SET @destDEPLOYMENT_ID = CONVERT(INT, @DEPLOYMENT_ID)
            SET @destDEPLOYMENT_TIME = CONVERT(DATETIME, @DEPLOYMENT_TIME)
            SET @destDEPTH = CONVERT(INT, @DEPTH)

        INSERT INTO TRANSFORM_GLOBALARCHIVE_DEPLOYMENT_POINTS
            (FID, CAMPAIGN_ID, DEPLOYMENT_ID, DEPLOYMENT_TIME, DESCRIPTION, [DEPTH], SITE, STATUS, SUCCESSFUL_COUNT,
            SUCCESSFUL_LENGTH, COORDINATES, OBSERVER, LOCATION, CAMPAIGN_NAME, CAMPAIGN_LINK, PROJECT_NAME,
            METHOD_NAME, COLOUR, GEOM)
            VALUES
            (@FID, @destCAMPAIGN_ID, @destDEPLOYMENT_ID, @destDEPLOYMENT_TIME, @DESCRIPTION, @destDEPTH, @SITE, @STATUS, @SUCCESSFUL_COUNT,
            @SUCCESSFUL_LENGTH, @COORDINATES, @OBSERVER, @LOCATION, @CAMPAIGN_NAME, @CAMPAIGN_LINK, @PROJECT_NAME,
            @METHOD_NAME, @COLOUR, @GEOM)

            FETCH NEXT FROM cGLOBALARCHIVEDATA INTO @FID, @CAMPAIGN_ID, @DEPLOYMENT_ID, @DEPLOYMENT_TIME, @DESCRIPTION, @DEPTH, @SITE, @STATUS,
                @SUCCESSFUL_COUNT, @SUCCESSFUL_LENGTH, @COORDINATES, @OBSERVER, @LOCATION, @CAMPAIGN_NAME, @CAMPAIGN_LINK, @PROJECT_NAME,
                @METHOD_NAME, @COLOUR, @GEOM
        END

        CLOSE cGLOBALARCHIVEDATA
        DEALLOCATE cGLOBALARCHIVEDATA
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION
        SELECT
            -1 AS Status,
            ERROR_NUMBER() AS ErrorNumber,
            ERROR_SEVERITY() AS ErrorSeverity,
            ERROR_STATE() AS ErrorState,
            ERROR_PROCEDURE() AS ErrorProcedure,
            ERROR_MESSAGE() AS ErrorMessage,
            ERROR_LINE() AS ErrorLine;
        RETURN
    END CATCH

    COMMIT TRANSACTION
    SELECT 0 as Status

END
