#!/usr/bin/env python3
"""Sanitise the raw schema.sql emitted by sqlpackage /Action:Script.

Steps:
  1. Strip DacFx's header (the leading "/* ... */" block contains a wall-clock
     timestamp that would force a non-functional diff on every recapture).
  2. Strip `:setvar DatabaseName "..."` and related sqlpackage defaults so
     the apply-time `-v DatabaseName=<target>` wins.
  3. Swap `:on error exit` → `:on error ignore` so the sqlcmd session
     continues past per-batch errors. The source DB has known-stale view
     bodies that reference renamed tables; we want the rest of the schema
     to land so dbinit can surface every failing batch in one pass instead
     of bailing at the first one. dbinit reports the Msg lines after apply.
  4. Optionally replace view bodies that reference unavailable linked servers
     with empty stubs — list managed via VIEW_STUBS below. Empty by default;
     extend if a recapture surfaces a linked-server reference Django would
     otherwise try to query locally.
  5. Validate that the resulting file contains no credentials or
     environment-specific principals. Fail loudly if anything slipped through.

Reads input path, writes output path. Exit 0 on success, non-zero on any
validation failure (output file is not written in that case).

Modelled on imas-craybase/scripts/sanitize-schema.py.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Patterns the committed artifact must not contain. Defence-in-depth — the
# sqlpackage /p:ExcludeObjectTypes flags should already prevent these, but
# we tripwire here so a regression in the capture command can't ship secrets.
FORBIDDEN = [
    (r"\bCREATE\s+LOGIN\b", "CREATE LOGIN statement (principals belong in env, not artifact)"),
    (r"\bCREATE\s+USER\b", "CREATE USER statement (principals belong in env, not artifact)"),
    (r"\bALTER\s+ROLE\b", "ALTER ROLE statement"),
    (r"\bGRANT\b\s+", "GRANT statement (permissions don't belong in committed schema)"),
    (r"\bDENY\b\s+", "DENY statement"),
    (r"\bREVOKE\b\s+", "REVOKE statement"),
    (r"\bPASSWORD\s*=", "PASSWORD= (credential material)"),
    (r"\bSID\s*=\s*0x", "SID=0x... (principal identifier)"),
    (r"UTAS\\", "UTAS\\ Windows principal"),
]

# Views that reference linked servers / external resources we don't have
# locally. Each entry is the view's bare name (e.g. "TAFI_PROD_CM_PERSON").
# The matching CREATE VIEW batch is replaced with an empty stub whose column
# shape is intentionally placeholder — code that queries the view will error
# at SELECT, which is the correct local behaviour for "not wired up locally".
#
# Empty by default for Seamap. Populate after the first capture surfaces any
# external-dependency views that need stubbing.
VIEW_STUBS: list[str] = []


def make_view_stub(view_name: str) -> str:
    return f"""\
-- Sanitised by scripts/sanitize-schema.py: original body referenced an
-- external resource (linked server / cross-DB) that doesn't resolve
-- locally. This stub stands in so the schema applies cleanly; queries
-- will error (correct behaviour for a not-wired-up local dependency).
CREATE VIEW [dbo].[{view_name}]
AS
SELECT CAST(NULL AS NVARCHAR(MAX)) AS placeholder
WHERE 1 = 0;
"""


def strip_dacfx_header(text: str) -> str:
    m = re.match(r"\A\s*/\*.*?\*/\s*", text, re.DOTALL)
    return text[m.end():] if m else text


def strip_scratch_setvars(text: str) -> str:
    # sqlpackage hardcodes the Script target DB name into `:setvar DatabaseName "..."`.
    # `:setvar` in a sqlcmd script overrides `-v` from the command line, so any
    # leftover line would silently override the apply-time target. Strip it
    # entirely; callers MUST pass `-v DatabaseName=...` (dbinit does this).
    text = re.sub(
        r'^:setvar\s+(?:DatabaseName|DefaultFilePrefix|DefaultDataPath|DefaultLogPath)\s+"[^"]+"\s*\r?\n',
        "",
        text,
        flags=re.MULTILINE,
    )
    banner = (
        "-- Generated by scripts/capture-schema.sh + scripts/sanitize-schema.py.\n"
        "-- Apply with: sqlcmd -i schema.sql -v DatabaseName=<target-db-name>\n"
        "-- `:setvar DatabaseName` has been stripped on purpose so the `-v` value wins.\n"
        "-- `:on error exit` has been swapped to `:on error ignore`: the source\n"
        "-- DB has stale view bodies pointing at renamed tables, and we want\n"
        "-- the rest of the schema to land. dbinit reports the failed batches.\n"
        "\n"
    )
    return banner + text


def relax_on_error(text: str) -> str:
    # sqlpackage emits `:on error exit` at the top of every Script output.
    # Swap it to `:on error ignore` so per-batch failures (mainly stale view
    # bodies on the source DB — e.g. SeamapAus_Boundaries_View references a
    # renamed table) don't abort the whole apply. dbinit's apply_schema()
    # parses the Msg lines afterwards and reports them.
    return re.sub(
        r"^[ \t]*:on\s+error\s+exit[ \t]*\r?\n",
        ":on error ignore\n",
        text,
        flags=re.IGNORECASE | re.MULTILINE,
    )


_GO_BATCH_SEPARATOR = re.compile(r"(?im)^[ \t]*GO[ \t]*(?:--.*)?(?:\r?\n|$)")


def _view_create_regex(view_name: str) -> re.Pattern[str]:
    return re.compile(
        rf"""(?imx)
        ^\s*CREATE\s+VIEW\s+
        (?:
            (?:\[dbo\]|dbo)\s*\.\s*
        )?
        (?:\[{re.escape(view_name)}\]|{re.escape(view_name)})
        \b
        """
    )


def replace_view_stubs(text: str) -> tuple[str, list[str]]:
    """Replace any GO-delimited CREATE VIEW batches listed in VIEW_STUBS."""
    if not VIEW_STUBS:
        return text, []

    patterns = {name: _view_create_regex(name) for name in VIEW_STUBS}
    stubbed: list[str] = []
    out: list[str] = []
    pos = 0

    for m in _GO_BATCH_SEPARATOR.finditer(text):
        batch = text[pos:m.start()]
        go = text[m.start():m.end()]
        for name, pat in patterns.items():
            if pat.search(batch):
                batch = make_view_stub(name).rstrip() + "\n"
                stubbed.append(name)
                break
        out.append(batch)
        out.append(go)
        pos = m.end()

    tail = text[pos:]
    for name, pat in patterns.items():
        if pat.search(tail):
            tail = make_view_stub(name).rstrip() + "\n"
            stubbed.append(name)
            break
    out.append(tail)

    return "".join(out), stubbed


def validate(text: str) -> list[str]:
    failures = []
    for pat, why in FORBIDDEN:
        matches = list(re.finditer(pat, text, re.IGNORECASE))
        if matches:
            line_num = text.count("\n", 0, matches[0].start()) + 1
            failures.append(f"  line {line_num}: {why} (pattern: {pat})")
    return failures


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"usage: {argv[0]} <raw.sql> <sanitised.sql>", file=sys.stderr)
        return 2

    src = Path(argv[1])
    dst = Path(argv[2])

    text = src.read_text(encoding="utf-8-sig")  # sqlpackage emits BOM

    text = strip_dacfx_header(text)
    text = strip_scratch_setvars(text)
    text = relax_on_error(text)
    text, stubbed = replace_view_stubs(text)

    failures = validate(text)
    if failures:
        print(
            "[sanitize] FAILED validation. Refusing to write output.",
            file=sys.stderr,
        )
        for f in failures:
            print(f, file=sys.stderr)
        return 1

    dst.write_text(text, encoding="utf-8")
    print(f"[sanitize] wrote {dst} ({dst.stat().st_size:,} bytes)")
    if stubbed:
        print(f"[sanitize] view(s) replaced with empty stub: {', '.join(stubbed)}")
    elif VIEW_STUBS:
        print(
            "[sanitize] warning: VIEW_STUBS configured but none matched — "
            "either the views are gone (drop them from VIEW_STUBS) or the "
            "regex no longer matches.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
