# Generated by Django 2.2.15 on 2021-09-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20171207_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='description',
        ),
    ]
