# Generated by Django 2.2.15 on 2021-10-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_remove_layer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('server_url', models.URLField()),
                ('attribution', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
