# Generated by Django 2.2.15 on 2022-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_baselayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='legend_url',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
