# Generated by Django 2.2.16 on 2022-01-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_layer_legend_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='legend_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
