# Generated by Django 2.2.16 on 2022-01-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20220127_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='metadata_url',
            field=models.URLField(max_length=250),
        ),
    ]
