# Generated by Django 2.2.16 on 2022-01-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20220127_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselayer',
            name='attribution',
            field=models.CharField(max_length=200),
        ),
    ]
