# Generated by Django 2.2.16 on 2022-05-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_layer_info_format_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselayer',
            name='sort_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
