# Generated by Django 4.2.27 on 2026-01-27 10:57

import catalogue.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_baselayer_sort_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpDepthZones',
            fields=[
                ('netname', models.CharField(db_column='NETNAME', max_length=255, primary_key=True, serialize=False)),
                ('resname', models.CharField(db_column='RESNAME', max_length=255)),
                ('zonename', models.CharField(db_column='ZONENAME', max_length=255)),
                ('min', models.IntegerField(db_column='MIN')),
                ('max', models.IntegerField(db_column='MAX')),
            ],
            options={
                'db_table': 'VW_AMP_DEPTHZONES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SquidleAnnotationsDataView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(db_column='NETNAME', max_length=255)),
                ('park', catalogue.models.EmptyStringToNoneField(blank=True, db_column='RESNAME', max_length=255, null=True)),
                ('depth_zone', catalogue.models.EmptyStringToNoneField(blank=True, db_column='ZONENAME', max_length=255, null=True)),
                ('highlights', models.BooleanField(db_column='HIGHLIGHTS')),
                ('annotations_data', models.TextField(db_column='ANNOTATIONS_DATA')),
            ],
            options={
                'db_table': 'VW_squidle_annotations_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseLayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_key', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('icon', catalogue.models.EmptyStringToNoneField(blank=True, max_length=255, null=True)),
                ('tooltip', catalogue.models.EmptyStringToNoneField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=255)),
                ('region_control_cql_property', models.CharField(max_length=255)),
                ('region_control_label', models.CharField(max_length=255)),
                ('region_control_data_type', models.CharField(choices=[('string', 'string'), ('number', 'number')], max_length=255)),
                ('region_control_controller_type', models.CharField(choices=[('slider', 'slider'), ('dropdown', 'dropdown'), ('multi-dropdown', 'multi-dropdown')], max_length=255)),
                ('region_control_icon', catalogue.models.EmptyStringToNoneField(blank=True, max_length=255, null=True)),
                ('region_control_tooltip', catalogue.models.EmptyStringToNoneField(blank=True, max_length=255, null=True)),
                ('region_control_default_value', catalogue.models.EmptyStringToNoneField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicPillLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', catalogue.models.EmptyStringToNoneField(blank=True, max_length=255, null=True)),
                ('dynamic_pill', models.ForeignKey(db_column='dynamicpill_id', on_delete=django.db.models.deletion.CASCADE, related_name='dynamicpill_layers', to='catalogue.dynamicpill')),
            ],
            options={
                'db_table': 'catalogue_dynamicpill_layers',
            },
        ),
        migrations.CreateModel(
            name='KeyedLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_key', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=254)),
                ('park', catalogue.models.EmptyStringToNoneField(blank=True, max_length=254, null=True)),
                ('habitat_state', models.FloatField(default=0)),
                ('bathymetry_state', models.FloatField(default=0)),
                ('habitat_observations_state', models.FloatField(default=0)),
                ('state_summary', models.TextField()),
                ('slug', models.CharField(max_length=255)),
                ('minx', models.FloatField(verbose_name='Max X')),
                ('miny', models.FloatField(verbose_name='Max Y')),
                ('maxx', models.FloatField(verbose_name='Min X')),
                ('maxy', models.FloatField(verbose_name='Min Y')),
            ],
        ),
        migrations.CreateModel(
            name='RichLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_label', models.CharField(max_length=255)),
                ('slider_label', models.CharField(max_length=255)),
                ('alternate_view_label', models.CharField(default='Alternate View', max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('tooltip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RichLayerAlternateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_key', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RichLayerControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cql_property', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'string'), ('number', 'number')], max_length=255)),
                ('controller_type', models.CharField(choices=[('slider', 'slider'), ('dropdown', 'dropdown'), ('multi-dropdown', 'multi-dropdown')], max_length=255)),
                ('icon', catalogue.models.EmptyStringToNoneField(blank=True, max_length=255, null=True)),
                ('tooltip', catalogue.models.EmptyStringToNoneField(blank=True, max_length=255, null=True)),
                ('default_value', catalogue.models.EmptyStringToNoneField(blank=True, max_length=255, null=True)),
                ('show_invalid', models.BooleanField(default=True, help_text='\n            <p>Show invalid values in the dropdown/multi-dropdown rich layer control:</p>\n            <ol>\n                <li>If true, invalid values are visible but disabled.</li>\n                <li>If false, invalid values are not visible.</li>\n            </ol>\n        ')),
                ('richlayer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='catalogue.richlayer')),
            ],
        ),
        migrations.CreateModel(
            name='RichLayerTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SaveState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hashstate', models.TextField(max_length=8000)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SquidleAnnotationsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(db_column='NETNAME', max_length=255)),
                ('park', catalogue.models.EmptyStringToNoneField(blank=True, db_column='RESNAME', max_length=255, null=True)),
                ('depth_zone', catalogue.models.EmptyStringToNoneField(blank=True, db_column='ZONENAME', max_length=255, null=True)),
                ('highlights', models.BooleanField(db_column='HIGHLIGHTS')),
                ('annotations_data', models.TextField(db_column='ANNOTATIONS_DATA')),
                ('error', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'squidle_annotations_data',
                'unique_together': {('network', 'park', 'depth_zone')},
            },
        ),
        migrations.RemoveField(
            model_name='layergrouppriority',
            name='group',
        ),
        migrations.RemoveField(
            model_name='layergrouppriority',
            name='layer',
        ),
        migrations.AddField(
            model_name='baselayer',
            name='layer_name',
            field=models.CharField(blank=True, help_text='Only required for WMS and WMTS layers', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='baselayer',
            name='layer_type',
            field=models.CharField(default='wms', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baselayer',
            name='max_zoom',
            field=models.IntegerField(blank=True, help_text='The base layer will be disabled beyond this zoom level in the application', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='crs',
            field=models.CharField(choices=[('EPSG:4326', 'EPSG:4326'), ('EPSG:3857', 'EPSG:3857'), ('EPSG:3112', 'EPSG:3112'), ('EPSG:3031', 'EPSG:3031')], default='EPSG:3112', max_length=10),
        ),
        migrations.AddField(
            model_name='layer',
            name='filter',
            field=models.CharField(blank=True, help_text='CQL filter to apply to the layer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='keywords',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('wms', 'wms'), ('tile', 'tile'), ('feature', 'feature'), ('map-server', 'map-server'), ('wms-non-tiled', 'wms-non-tiled'), ('esri-vector-tile', 'esri-vector-tile'), ('wmts', 'wmts'), ('esri-image-map', 'esri-image-map')], default='wms', help_text='\n            <p>Seamap accommodates 7 different types of map layer:</p>\n            <ol>\n                <li><code>wms</code>: standard OGC/MapServer wms or WMSServer</li>\n                <li><code>feature</code>: vector-styled layer from ESRI ArcGIS server</li>\n                <li><code>map-server</code>: not <code>tile</code> or <code>wms</code> layer from ESRI ArcGIS MapServer</li>\n                <li><code>tile</code>: tile server</li>\n                <li><code>wms-non-tiled</code>: special case where we want a WMS request to be made of a single image of the layer, rather than a series of tiles. This is less efficient but is used sometimes for layers that use a global render (e.g. heatmaps)</li>\n                <li><code>esri-vector-tile</code>: For ESRI VectorTileServer layers. Rendered with <a href="https://developers.arcgis.com/esri-leaflet/api-reference/esri-leaflet-vector/vector-layer/">L.esri.Vector.vectorTileLayer</a></li>\n                <li><code>esri-image-map</code>: For ESRI ImageServer layers. Rendered with <a href="https://developers.arcgis.com/esri-leaflet/api-reference/esri-leaflet/image-map-layer/">L.esri.imageMapLayer</a></li>\n            </ol>\n            <p>Extra info:</p>\n            <ul>\n                <li><code>wms</code> and <code>wms-non-tiled</code> (/wms and /WMSServer) layers require a <code>server_url</code> (e.g. <a target="_blank" rel="noopener noreferrer" href="https://geoserver.imas.utas.edu.au/geoserver/wms">https://geoserver.imas.utas.edu.au/geoserver/wms</a>) and <code>layer_name</code> (e.g. seamap:SeamapAus_TAS_AbHab_substrata)</li>\n                <li><code>feature</code> layers (/FeatureServer) <i>only&nbsp;</i>require a <code>server_url</code>. The layer is identified as a trailing /x numeral: e.g. <a target="_blank" rel="noopener noreferrer" href="https://services3.arcgis.com/nbGeuo4JHMRYW4oj/arcgis/rest/services/Biologically_Important_Areas/FeatureServer/2">https://services3.arcgis.com/nbGeuo4JHMRYW4oj/arcgis/rest/services/Biologically_Important_Areas/FeatureServer/2</a></li>\n                <li><code>map-server</code> layers (from /MapServer) are configured the same as <code>feature</code></li>\n                <li><code>tile</code> layers&nbsp;<i>only</i> require a <code>server_url</code>, and must identify the x/y/z tile ordering in the <code>server_url</code>: e.g. <a target="_blank" rel="noopener noreferrer" href="https://services1.arcgis.com/wfNKYeHsOyaFyPw3/ArcGIS/rest/services/AIS_2020_Vessel_Tracks/MapServer/tile/{z}/{y}/{x}">https://services1.arcgis.com/wfNKYeHsOyaFyPw3/ArcGIS/rest/services/AIS_2020_Vessel_Tracks/MapServer/tile/{z}/{y}/{x}</a></li>\n            </ul>\n        ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='metadata_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='regenerate_preview',
            field=models.BooleanField(default=True, help_text='Dictates if a layer should generate a new layer preview each week, even if a preview already exists. If no preview image exists for the layer, this property will be ignored.'),
        ),
        migrations.AddField(
            model_name='layer',
            name='style',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='tooltip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baselayer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dataclassification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='habitatdescriptor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='info_format_type',
            field=models.IntegerField(choices=[(1, '1 (text/html)'), (2, '2 (application/json)'), (3, '3 (none)'), (4, '4 (feature)'), (5, '5 (xml)'), (6, '6 (map-server)')], help_text='\n            <p>Specifies format to retrieve <code>GetFeatureInfo</code> request (click-for-popup). Most IMAS-hosted layers will have a HTML styled popup configured (content.ftl file), but many external layers do not have this configured, so GFI requests <code>text/html</code> and unformatted text is returned. This column enables a flag to request <code>GetFeatureInfo</code> in 6 possible formats (allowed values: 1-6):</p>\n            <ol>\n                <li><code>GetFeatureInfo</code> as <code>INFO_FORMAT</code>=<code>text/html</code> (for “styled” popups)</li>\n                <li><code>GetFeatureInfo</code> as <code>INFO_FORMAT</code>=<code>application/json</code> (for unstyled popups that can be represented in tabular format – defaults to a grey/white striped table using raw JSON)</li>\n                <li>No GetFeatureInfo (displays message “no info available” – for unstyled data which can’t be represented in json)</li>\n                <li>Feature info specifically for ESRI FeatureServer layers: will have <code>layer_type</code> = <code>feature</code></li>\n                <li>Feature info specifically for List (+ maybe others) that return results in XML - will display similar to 2 in roughly styled table</li>\n                <li>Feature info for ESRI MapServer layers (though not <code>tile</code> or <code>wms</code> MapServer layers). Will have <code>layer_type</code> = <code>map-server</code></li>\n            </ol>\n        '),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='LayerGroup',
        ),
        migrations.DeleteModel(
            name='LayerGroupPriority',
        ),
        migrations.AddField(
            model_name='richlayertimeline',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.layer'),
        ),
        migrations.AddField(
            model_name='richlayertimeline',
            name='richlayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline', to='catalogue.richlayer'),
        ),
        migrations.AddField(
            model_name='richlayeralternateview',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.layer'),
        ),
        migrations.AddField(
            model_name='richlayeralternateview',
            name='richlayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternate_views', to='catalogue.richlayer'),
        ),
        migrations.AddField(
            model_name='richlayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.layer'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.layer'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='region_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.regionreport'),
        ),
        migrations.AddField(
            model_name='keyedlayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.layer'),
        ),
        migrations.AddField(
            model_name='dynamicpilllayer',
            name='layer',
            field=models.ForeignKey(db_column='layer_id', on_delete=django.db.models.deletion.CASCADE, to='catalogue.layer'),
        ),
        migrations.AddField(
            model_name='dynamicpill',
            name='layers',
            field=models.ManyToManyField(through='catalogue.DynamicPillLayer', to='catalogue.layer'),
        ),
        migrations.AddField(
            model_name='baselayer',
            name='layer_group',
            field=models.ForeignKey(blank=True, db_column='layer_group', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.baselayergroup'),
        ),
    ]
