# Generated by Django 3.2.25 on 2026-02-02 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_ampdepthzones_squidleannotationsdataview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richlayer',
            name='alternate_view_label',
            field=models.CharField(blank=True, default='Alternate View', max_length=255),
        ),
        migrations.AlterField(
            model_name='richlayer',
            name='slider_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='RichLayerSideBySideView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_key', models.CharField(blank=True, max_length=10, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.layer')),
                ('richlayer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='side_by_side_views', to='catalogue.richlayer')),
            ],
        ),
    ]
