# Generated by Django 3.2.25 on 2026-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20260202_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='download_format',
            field=models.CharField(blank=True, choices=[(None, None), ('wfs', 'wfs'), ('wcs', 'wcs')], max_length=200, null=True),
        ),
    ]
