# Generated by Django 3.2.25 on 2026-05-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_layer_download_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('wms', 'wms'), ('tile', 'tile'), ('feature', 'feature'), ('map-server', 'map-server'), ('wms-non-tiled', 'wms-non-tiled'), ('esri-vector-tile', 'esri-vector-tile'), ('wmts', 'wmts'), ('esri-image-map', 'esri-image-map'), ('wms-timeseries', 'wms-timeseries')], help_text='\n            <p>Seamap accommodates 7 different types of map layer:</p>\n            <ol>\n                <li><code>wms</code>: standard OGC/MapServer wms or WMSServer</li>\n                <li><code>feature</code>: vector-styled layer from ESRI ArcGIS server</li>\n                <li><code>map-server</code>: not <code>tile</code> or <code>wms</code> layer from ESRI ArcGIS MapServer</li>\n                <li><code>tile</code>: tile server</li>\n                <li><code>wms-non-tiled</code>: special case where we want a WMS request to be made of a single image of the layer, rather than a series of tiles. This is less efficient but is used sometimes for layers that use a global render (e.g. heatmaps)</li>\n                <li><code>esri-vector-tile</code>: For ESRI VectorTileServer layers. Rendered with <a href="https://developers.arcgis.com/esri-leaflet/api-reference/esri-leaflet-vector/vector-layer/">L.esri.Vector.vectorTileLayer</a></li>\n                <li><code>esri-image-map</code>: For ESRI ImageServer layers. Rendered with <a href="https://developers.arcgis.com/esri-leaflet/api-reference/esri-leaflet/image-map-layer/">L.esri.imageMapLayer</a></li>\n                <li><code>wms-timeseries</code>: </li>\n            </ol>\n            <p>Extra info:</p>\n            <ul>\n                <li><code>wms</code> and <code>wms-non-tiled</code> (/wms and /WMSServer) layers require a <code>server_url</code> (e.g. <a target="_blank" rel="noopener noreferrer" href="https://geoserver.imas.utas.edu.au/geoserver/wms">https://geoserver.imas.utas.edu.au/geoserver/wms</a>) and <code>layer_name</code> (e.g. seamap:SeamapAus_TAS_AbHab_substrata)</li>\n                <li><code>feature</code> layers (/FeatureServer) <i>only&nbsp;</i>require a <code>server_url</code>. The layer is identified as a trailing /x numeral: e.g. <a target="_blank" rel="noopener noreferrer" href="https://services3.arcgis.com/nbGeuo4JHMRYW4oj/arcgis/rest/services/Biologically_Important_Areas/FeatureServer/2">https://services3.arcgis.com/nbGeuo4JHMRYW4oj/arcgis/rest/services/Biologically_Important_Areas/FeatureServer/2</a></li>\n                <li><code>map-server</code> layers (from /MapServer) are configured the same as <code>feature</code></li>\n                <li><code>tile</code> layers&nbsp;<i>only</i> require a <code>server_url</code>, and must identify the x/y/z tile ordering in the <code>server_url</code>: e.g. <a target="_blank" rel="noopener noreferrer" href="https://services1.arcgis.com/wfNKYeHsOyaFyPw3/ArcGIS/rest/services/AIS_2020_Vessel_Tracks/MapServer/tile/{z}/{y}/{x}">https://services1.arcgis.com/wfNKYeHsOyaFyPw3/ArcGIS/rest/services/AIS_2020_Vessel_Tracks/MapServer/tile/{z}/{y}/{x}</a></li>\n            </ul>\n        ', max_length=200),
        ),
        migrations.AlterField(
            model_name='layer',
            name='metadata_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
