# Generated by Django 3.2.25 on 2026-05-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_auto_20260518_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='download_format',
            field=models.CharField(blank=True, choices=[(None, None), ('wfs', 'wfs'), ('wcs', 'wcs'), ('thredds-wcs', 'thredds-wcs')], max_length=200, null=True),
        ),
    ]
