# Generated by Django 3.2.25 on 2026-05-28 04:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_alter_layer_download_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='metadata_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
