# Generated by Django 4.2.28 on 2026-08-03 03:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_layer_metadata_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='metadata_content',
        ),
        migrations.AlterField(
            model_name='layer',
            name='metadata_summary',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
