-- Generated by manage.py dump_migration_baseline.
-- Baseline rows for django_migrations, derived from the codebase's
-- on-disk migration graph at capture time. Apply with:
--   sqlcmd -i migrations_baseline.sql -v DatabaseName=<target>
-- Rows: 51
USE [$(DatabaseName)];
GO
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('admin', '0001_initial', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('admin', '0002_logentry_remove_auto_add', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('admin', '0003_logentry_add_action_flag_choices', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0001_initial', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0002_alter_permission_name_max_length', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0003_alter_user_email_max_length', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0004_alter_user_username_opts', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0005_alter_user_last_login_null', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0006_require_contenttypes_0002', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0007_alter_validators_add_error_messages', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0008_alter_user_username_max_length', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0009_alter_user_last_name_max_length', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0010_alter_group_name_max_length', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0011_update_proxy_permissions', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('auth', '0012_alter_user_first_name_max_length', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0001_initial', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0002_auto_20170217_1206', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0003_layer_detail_resolution', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0004_auto_20170315_1350', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0005_auto_20170417_1535', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0006_auto_20170417_1548', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0007_auto_20170419_1156', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0008_auto_20170428_1815', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0009_auto_20170517_1153', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0010_auto_20170525_1504', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0011_layer_layer_group', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0012_auto_20170602_1608', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0013_auto_20170615_1156', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0014_auto_20170622_1153', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0015_habitatdescriptor', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0016_layer_sort_key', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0017_layer_detail_layer', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0018_organisation_logo', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0019_auto_20171107_1701', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0020_layer_table_name', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0021_auto_20171207_1508', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0022_auto_20171207_1625', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0023_remove_layer_description', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0024_baselayer', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0025_layer_legend_url', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0026_auto_20220127_0006', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0027_auto_20220127_0007', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0028_auto_20220127_0009', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0029_layer_info_format_type', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0030_baselayer_sort_key', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0031_ampdepthzones_squidleannotationsdataview_and_more', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0032_auto_20260202_0500', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('catalogue', '0033_layer_download_format', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('contenttypes', '0001_initial', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('contenttypes', '0002_remove_content_type_name', '2000-01-01T00:00:00');
INSERT INTO [dbo].[django_migrations] ([app], [name], [applied]) VALUES ('sessions', '0001_initial', '2000-01-01T00:00:00');
GO
